#!/bin/sh

read ACTION

case "$ACTION" in
        logout)
                i3-msg exit
                ;;
        shutdown)
                systemctl poweroff
                ;;
        hibernate)
                systemctl hibernate
                ;;
        reboot)
                systemctl reboot
                ;;
esac

